services:
  frontend:
    build:
      context: front_end
    ports:
      - "8501:8501"
    networks:
      - my-network
  backend:
    build:
      context: back_end
    networks:
      - my-network
networks:
  my-network:
    driver: bridge
